sonar.projectKey=VictorHermon_full-cycle-sonarcloud
sonar.organization=victorhermon

sonar.sources=.

sonar.exclusions=**/*test.go

sonar.tests=.
sonar.test.inclusions=**/*test.go

sonar.go.coverage.reportPaths=coverage.out